# Generated by Django 4.0.5 on 2022-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('beekepingNature', models.CharField(choices=[('Álló', 'Standing'), ('Vándor', 'Migration')], default='Álló', max_length=8)),
                ('smallProducerRegNumber', models.CharField(max_length=7)),
            ],
        ),
    ]
