# Generated by Django 4.0.5 on 2022-06-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meheszet_app', '0002_breedings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breedings',
            new_name='Breeding',
        ),
    ]
