# Generated by Django 4.0.5 on 2022-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meheszet_app', '0003_rename_breedings_breeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedingcode', models.CharField(max_length=7)),
                ('beehivenumber', models.CharField(max_length=4)),
                ('quenbeecolor', models.CharField(choices=[('NULL', 'Kérlek válassz szint'), ('BLUE', 'Kék'), ('WHITE', 'Fehér'), ('RED', 'Piros'), ('YELLOW', 'Sárga'), ('GREEN', 'Zöld')], max_length=7)),
                ('quenbeeyear', models.CharField(max_length=4)),
                ('beehivestrength', models.CharField(choices=[('NULL', 'Kérlek válassz erősséget'), ('WEAK', 'Gyenge'), ('AVERAGE', 'Átlagos'), ('STRONG', 'Erős')], max_length=10)),
                ('typeofhive', models.CharField(choices=[('NULL', 'Kérlek válassz'), ('LANGSTROTH', 'Langstroth'), ('WARRE', 'Warre'), ('NEISZER', 'Neiszer-féle ikerkaptár'), ('KISBOCONADI', 'Kis Boczonádi'), ('BALOGHBALINT', 'Balogh Bálint-féle kaptár'), ('MOGOR', 'Mogor'), ('HUNOR', 'Hunor'), ('KOZEPBOCONADI', 'Közép Boczonádi'), ('DADANTBLATT', 'Dadant-Blatt féle kaptár'), ('ZANDER', 'Zander féle'), ('IGNACZ', 'Ignácz-féle Kaptár'), ('DEBRECENI', 'Debreceni kaptár'), ('NAGYBOCONADI', 'Nagy Boczonádi')], max_length=25)),
            ],
        ),
    ]
