# Generated by Django 4.0.5 on 2022-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meheszet_app', '0004_beehive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beehive',
            name='beehivestrength',
            field=models.CharField(choices=[('Kérlek válassz erősséget', 'NULL'), ('Gyenge', 'Gyenge'), ('Átlagos', 'Átlagos'), ('Erős', 'Erős')], max_length=24),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='quenbeecolor',
            field=models.CharField(choices=[('Kérlek válassz szint', 'NULL'), ('Kék', 'Kék'), ('Fehér', 'Fehér'), ('Piros', 'Piros'), ('Sárga', 'Sárga'), ('Zöld', 'Zöld')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='typeofhive',
            field=models.CharField(choices=[('NULL', 'Kérlek válassz'), ('Langstroth', 'Langstroth'), ('Warre', 'Warre'), ('Neiszer', 'Neiszer-féle ikerkaptár'), ('Kis Boczonádi', 'Kis Boczonádi'), ('Balogh Bálint féle', 'Balogh Bálint-féle kaptár'), ('Mogor', 'Mogor'), ('Hunor', 'Hunor'), ('Közép Boczonádi', 'Közép Boczonádi'), ('Dadant-Blatt féle', 'Dadant-Blatt féle kaptár'), ('Zander', 'Zander féle'), ('Ignácz-féle', 'Ignácz-féle Kaptár'), ('Debreceni', 'Debreceni kaptár'), ('Nagy Boczonádi', 'Nagy Boczonádi')], max_length=25),
        ),
    ]
