# Generated by Django 4.0.5 on 2022-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meheszet_app', '0006_alter_adduser_id_alter_beehive_id_alter_breeding_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beehive',
            old_name='quenbeecolor',
            new_name='queenbeecolor',
        ),
        migrations.RenameField(
            model_name='beehive',
            old_name='quenbeeyear',
            new_name='queenbeeyear',
        ),
    ]
